export const PATHS = {
  ROOT: '/',
  SWAP: '/swap',
  VAULTS: '/vaults',
  VAULT: '/vault',
  STAKER_PAGE: '/staker',
  FRAKTIONALIZE: '/fraktionalize',
  WALLET: '/wallet',
  PAGE_404: '/404',
  COLLECTIONS: '/collections',
  COLLECTION: '/collection',
  VAULT_PUBKEY: '/:vaultPubkey',
  WALLET_PUBKEY: '/:walletPubkey',
  COLLECTION_NAME: '/:collectionName',
};
